#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrderManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OrderManagement")]
	public partial class DataClasses_OMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void InsertCustomer_cls(Customer_cls instance);
    partial void UpdateCustomer_cls(Customer_cls instance);
    partial void DeleteCustomer_cls(Customer_cls instance);
    partial void InsertMerchandise_cls(Merchandise_cls instance);
    partial void UpdateMerchandise_cls(Merchandise_cls instance);
    partial void DeleteMerchandise_cls(Merchandise_cls instance);
    partial void InsertOrder_cls(Order_cls instance);
    partial void UpdateOrder_cls(Order_cls instance);
    partial void DeleteOrder_cls(Order_cls instance);
    #endregion
		
		public DataClasses_OMDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OM_DATA"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_OMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_OMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_OMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_OMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer_cls> Customer_cls
		{
			get
			{
				return this.GetTable<Customer_cls>();
			}
		}
		
		public System.Data.Linq.Table<Merchandise_cls> Merchandise_cls
		{
			get
			{
				return this.GetTable<Merchandise_cls>();
			}
		}
		
		public System.Data.Linq.Table<Order_cls> Order_cls
		{
			get
			{
				return this.GetTable<Order_cls>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Customer")]
	public partial class Customer_cls : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _customer_code;
		
		private string _customer;
		
		private EntitySet<Order_cls> _Order_cls;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncustomer_codeChanging(int value);
    partial void Oncustomer_codeChanged();
    partial void OncustomerChanging(string value);
    partial void OncustomerChanged();
    #endregion
		
		public Customer_cls()
		{
			this._Order_cls = new EntitySet<Order_cls>(new Action<Order_cls>(this.attach_Order_cls), new Action<Order_cls>(this.detach_Order_cls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_code", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int customer_code
		{
			get
			{
				return this._customer_code;
			}
			set
			{
				if ((this._customer_code != value))
				{
					this.Oncustomer_codeChanging(value);
					this.SendPropertyChanging();
					this._customer_code = value;
					this.SendPropertyChanged("customer_code");
					this.Oncustomer_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer", DbType="NVarChar(50)")]
		public string customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				if ((this._customer != value))
				{
					this.OncustomerChanging(value);
					this.SendPropertyChanging();
					this._customer = value;
					this.SendPropertyChanged("customer");
					this.OncustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_cls_Order_cls", Storage="_Order_cls", ThisKey="customer_code", OtherKey="customer_code")]
		public EntitySet<Order_cls> Order_cls
		{
			get
			{
				return this._Order_cls;
			}
			set
			{
				this._Order_cls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Order_cls(Order_cls entity)
		{
			this.SendPropertyChanging();
			entity.Customer_cls = this;
		}
		
		private void detach_Order_cls(Order_cls entity)
		{
			this.SendPropertyChanging();
			entity.Customer_cls = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Merchandise")]
	public partial class Merchandise_cls : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _merchandise_code;
		
		private string _merchandise;
		
		private EntitySet<Order_cls> _Order_cls;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmerchandise_codeChanging(int value);
    partial void Onmerchandise_codeChanged();
    partial void OnmerchandiseChanging(string value);
    partial void OnmerchandiseChanged();
    #endregion
		
		public Merchandise_cls()
		{
			this._Order_cls = new EntitySet<Order_cls>(new Action<Order_cls>(this.attach_Order_cls), new Action<Order_cls>(this.detach_Order_cls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_merchandise_code", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int merchandise_code
		{
			get
			{
				return this._merchandise_code;
			}
			set
			{
				if ((this._merchandise_code != value))
				{
					this.Onmerchandise_codeChanging(value);
					this.SendPropertyChanging();
					this._merchandise_code = value;
					this.SendPropertyChanged("merchandise_code");
					this.Onmerchandise_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_merchandise", DbType="NVarChar(50)")]
		public string merchandise
		{
			get
			{
				return this._merchandise;
			}
			set
			{
				if ((this._merchandise != value))
				{
					this.OnmerchandiseChanging(value);
					this.SendPropertyChanging();
					this._merchandise = value;
					this.SendPropertyChanged("merchandise");
					this.OnmerchandiseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Merchandise_cls_Order_cls", Storage="_Order_cls", ThisKey="merchandise_code", OtherKey="merchandise_code")]
		public EntitySet<Order_cls> Order_cls
		{
			get
			{
				return this._Order_cls;
			}
			set
			{
				this._Order_cls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Order_cls(Order_cls entity)
		{
			this.SendPropertyChanging();
			entity.Merchandise_cls = this;
		}
		
		private void detach_Order_cls(Order_cls entity)
		{
			this.SendPropertyChanging();
			entity.Merchandise_cls = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Order")]
	public partial class Order_cls : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _order_code;
		
		private int _customer_code;
		
		private int _merchandise_code;
		
		private System.Nullable<int> _quantity;
		
		private System.DateTime _deadline;
		
		private string _status;
		
		private EntityRef<Customer_cls> _Customer_cls;
		
		private EntityRef<Merchandise_cls> _Merchandise_cls;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorder_codeChanging(int value);
    partial void Onorder_codeChanged();
    partial void Oncustomer_codeChanging(int value);
    partial void Oncustomer_codeChanged();
    partial void Onmerchandise_codeChanging(int value);
    partial void Onmerchandise_codeChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void OndeadlineChanging(System.DateTime value);
    partial void OndeadlineChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public Order_cls()
		{
			this._Customer_cls = default(EntityRef<Customer_cls>);
			this._Merchandise_cls = default(EntityRef<Merchandise_cls>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_code", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int order_code
		{
			get
			{
				return this._order_code;
			}
			set
			{
				if ((this._order_code != value))
				{
					this.Onorder_codeChanging(value);
					this.SendPropertyChanging();
					this._order_code = value;
					this.SendPropertyChanged("order_code");
					this.Onorder_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_code", DbType="Int NOT NULL")]
		public int customer_code
		{
			get
			{
				return this._customer_code;
			}
			set
			{
				if ((this._customer_code != value))
				{
					if (this._Customer_cls.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncustomer_codeChanging(value);
					this.SendPropertyChanging();
					this._customer_code = value;
					this.SendPropertyChanged("customer_code");
					this.Oncustomer_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_merchandise_code", DbType="Int NOT NULL")]
		public int merchandise_code
		{
			get
			{
				return this._merchandise_code;
			}
			set
			{
				if ((this._merchandise_code != value))
				{
					if (this._Merchandise_cls.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmerchandise_codeChanging(value);
					this.SendPropertyChanging();
					this._merchandise_code = value;
					this.SendPropertyChanged("merchandise_code");
					this.Onmerchandise_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deadline", DbType="Date NOT NULL")]
		public System.DateTime deadline
		{
			get
			{
				return this._deadline;
			}
			set
			{
				if ((this._deadline != value))
				{
					this.OndeadlineChanging(value);
					this.SendPropertyChanging();
					this._deadline = value;
					this.SendPropertyChanged("deadline");
					this.OndeadlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_cls_Order_cls", Storage="_Customer_cls", ThisKey="customer_code", OtherKey="customer_code", IsForeignKey=true)]
		public Customer_cls Customer_cls
		{
			get
			{
				return this._Customer_cls.Entity;
			}
			set
			{
				Customer_cls previousValue = this._Customer_cls.Entity;
				if (((previousValue != value) 
							|| (this._Customer_cls.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customer_cls.Entity = null;
						previousValue.Order_cls.Remove(this);
					}
					this._Customer_cls.Entity = value;
					if ((value != null))
					{
						value.Order_cls.Add(this);
						this._customer_code = value.customer_code;
					}
					else
					{
						this._customer_code = default(int);
					}
					this.SendPropertyChanged("Customer_cls");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Merchandise_cls_Order_cls", Storage="_Merchandise_cls", ThisKey="merchandise_code", OtherKey="merchandise_code", IsForeignKey=true)]
		public Merchandise_cls Merchandise_cls
		{
			get
			{
				return this._Merchandise_cls.Entity;
			}
			set
			{
				Merchandise_cls previousValue = this._Merchandise_cls.Entity;
				if (((previousValue != value) 
							|| (this._Merchandise_cls.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Merchandise_cls.Entity = null;
						previousValue.Order_cls.Remove(this);
					}
					this._Merchandise_cls.Entity = value;
					if ((value != null))
					{
						value.Order_cls.Add(this);
						this._merchandise_code = value.merchandise_code;
					}
					else
					{
						this._merchandise_code = default(int);
					}
					this.SendPropertyChanged("Merchandise_cls");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
